
-- ALTER TABLE [dbo].[T_Benutzer] DROP COLUMN [_BE_LCID];

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS AS isc WHERE isc.TABLE_SCHEMA = 'dbo' AND isc.TABLE_NAME = 'T_Benutzer' AND isc.COLUMN_NAME = '_BE_LCID') 
BEGIN
	ALTER TABLE [dbo].[T_Benutzer] 
	ADD [_BE_LCID] AS (CASE T_Benutzer.BE_Language WHEN 'FR' THEN 4108 WHEN 'IT' THEN 2064 WHEN 'EN' THEN 1033 ELSE 2055 END) PERSISTED 
	; 
END 

GO

-- SELECT * FROM T_Benutzer 
